// <auto-generated />
namespace WebApplication7.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class DepartmentModelAdded1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DepartmentModelAdded1));
        
        string IMigrationMetadata.Id
        {
            get { return "202001280915296_DepartmentModelAdded1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
